# Generated by Django 5.1.4 on 2025-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_completed_at_remove_job_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
