# Generated by Django 5.1.4 on 2025-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
